### ISSUE TITLE
Edit to ux-refresh: Adjust Product box styling

### ISSUE THREAD

**Issue by sonejah21** [projectjellyfish/ux#272]
Product boxes (at left) styling should be exactly like Project boxes (at right).

![uploads/d2abdb68-35b6-4f4c-94fb-d12a5b0c21b7/screen_shot_2015-03-09_at_3.13.16_pm.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd2abdb68-35b6-4f4c-94fb-d12a5b0c21b7%2Fscreen_shot_2015-03-09_at_3.13.16_pm.png)

**Comment by stackus** [comment]
Specifically what is it that should be styled the same? Minor styling aside I thinking col-xs-x, col-sm-x styles.

Part of the reason product boxes used a different structure was because there existed a toggle to switch between the album view and a row view. This could be complication when restructuring them.

**Comment by sonejah21** [comment]
The styling was just to make the boxes the same style, removing the box-shadow. I made the ticket for this so I wouldn't forget to do it. See screenshot of updated style:
![uploads/4f3a45c6-dfd9-4d98-bddb-e66b6972dc3c/Screen Shot 2015-03-10 at 10.44.14 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4f3a45c6-dfd9-4d98-bddb-e66b6972dc3c%2FScreen+Shot+2015-03-10+at+10.44.14+AM.png)
